# no version needed since 2020

services:
  jekyll:
    image: bretfisher/jekyll-serve
    command: bundle exec jekyll s --force_polling -H 0.0.0.0 -P 4000 --livereload
    volumes:
      - .:/site
    ports:
      - '4000:4000'
      - '35729:35729'
